// Mock data for FLOWLOG app

// === MULTI-USER SYSTEM ===
// Two demo users for account switching feature

export const users = {
  niranjan: {
    id: 'user-niranjan',
    name: 'Niranjan Raghavan',
    email: 'niranjan.raghavan@theprocess.com',
    role: 'UI/UX Designer',
    team: 'Designer Team',
    employeeId: 'EMP-5421',
    avatar: 'https://images.unsplash.com/photo-1667839410402-c4266dc7f1d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=400',
    streak: 15,
    flowPoints: 4250,
    flowPointsGoal: 500,
    level: 9,
    xp: 2340,
  },
  vijay: {
    id: 'user-vijay',
    name: 'Vijay Kumar',
    email: 'vijay.kumar@theprocess.com',
    role: 'QA Engineer',
    team: 'Testing Team',
    employeeId: 'EMP-7821',
    avatar: 'https://images.unsplash.com/photo-1681164315430-6159b2361615?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=400',
    streak: 8,
    flowPoints: 2890,
    flowPointsGoal: 500,
    level: 6,
    xp: 1620,
  },
};

export const mockUser = {
  id: '1',
  name: 'Arjun',
  email: 'arjun@theprocess.com',
  role: 'Senior Developer',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
  streak: 12,
  flowPoints: 3420,
  flowPointsGoal: 500,
  level: 7,
  xp: 1850,
};

// ERP Work Orders with full details
// NOW WITH OWNER FIELD - Shared across all users
export const mockWorkOrders = [
  {
    id: 'WO-2025-001',
    number: 'WO-2025-001',
    name: 'Mobile App Redesign',
    client: 'TechCorp Inc.',
    status: 'In Progress',
    priority: 'High',
    type: 'direct', // direct or sequence
    billable: true,
    rate: 950,
    currency: '₹',
    startDate: '2025-11-10',
    dueDate: '2025-12-20',
    estimatedHours: 120,
    actualHours: 45.5,
    billingPolicy: 'Per hour worked',
    description: 'Complete redesign of mobile application with new UI/UX',
    lastActivity: '2 hours ago',
    owner: 'user-niranjan', // Niranjan owns this
    ownerName: 'Niranjan Raghavan',
    department: 'Design',
  },
  {
    id: 'WO-2025-002',
    number: 'WO-2025-002',
    name: 'API Integration - Payment Gateway',
    client: 'StartupXYZ',
    status: 'In Progress',
    priority: 'High',
    type: 'direct',
    billable: true,
    rate: 1150,
    currency: '₹',
    startDate: '2025-11-15',
    dueDate: '2025-12-15',
    estimatedHours: 60,
    actualHours: 18.5,
    billingPolicy: 'Per project milestone',
    description: 'Integration of third-party payment gateway with existing system',
    lastActivity: '1 day ago',
    owner: 'user-vijay', // Vijay owns this
    ownerName: 'Vijay Kumar',
    department: 'Engineering',
  },
  {
    id: 'WO-2025-003',
    number: 'WO-2025-003',
    name: 'Database Migration Project',
    client: 'Enterprise Solutions Ltd.',
    status: 'In Progress',
    priority: 'Critical',
    type: 'sequence', // Process sequence type
    billable: true,
    rate: 1200,
    currency: '₹',
    startDate: '2025-11-10',
    dueDate: '2026-02-01',
    estimatedHours: 180,
    actualHours: 32,
    billingPolicy: 'Per step completion',
    description: 'Multi-phase database migration from legacy to cloud infrastructure',
    lastActivity: '3 days ago',
    owner: 'user-vijay', // Vijay owns this
    ownerName: 'Vijay Kumar',
    department: 'Engineering',
    processSteps: [
      { id: 'step-1', name: 'Assessment & Planning', status: 'Completed', hours: 12 },
      { id: 'step-2', name: 'Data Backup', status: 'Completed', hours: 8 },
      { id: 'step-3', name: 'Schema Migration', status: 'In Progress', hours: 12 },
      { id: 'step-4', name: 'Data Migration', status: 'Pending', hours: 0 },
      { id: 'step-5', name: 'Testing & Validation', status: 'Pending', hours: 0 },
    ],
  },
  {
    id: 'WO-2025-004',
    number: 'WO-2025-004',
    name: 'UI Component Library Development',
    client: 'Internal - The Process',
    status: 'In Progress',
    priority: 'Medium',
    type: 'direct',
    billable: false,
    rate: 0,
    currency: '₹',
    startDate: '2025-11-01',
    dueDate: '2025-12-30',
    estimatedHours: 200,
    actualHours: 87,
    billingPolicy: 'Internal project',
    description: 'Build reusable component library for all internal projects',
    lastActivity: '5 hours ago',
    owner: 'user-niranjan', // Niranjan owns this
    ownerName: 'Niranjan Raghavan',
    department: 'Design',
  },
  {
    id: 'WO-2025-005',
    number: 'WO-2025-005',
    name: 'E-commerce Platform Setup',
    client: 'RetailCo India',
    status: 'Not Started',
    priority: 'Medium',
    type: 'sequence',
    billable: true,
    rate: 1050,
    currency: '₹',
    startDate: '2025-11-20',
    dueDate: '2026-02-28',
    estimatedHours: 300,
    actualHours: 0,
    billingPolicy: 'Per milestone',
    description: 'Full e-commerce platform with inventory management',
    lastActivity: 'Not started',
    owner: 'user-niranjan', // Niranjan owns this
    ownerName: 'Niranjan Raghavan',
    department: 'Design',
    processSteps: [
      { id: 'step-1', name: 'Requirements Gathering', status: 'Pending', hours: 0 },
      { id: 'step-2', name: 'Platform Setup', status: 'Pending', hours: 0 },
      { id: 'step-3', name: 'Payment Integration', status: 'Pending', hours: 0 },
      { id: 'step-4', name: 'Inventory System', status: 'Pending', hours: 0 },
      { id: 'step-5', name: 'Testing & Launch', status: 'Pending', hours: 0 },
    ],
  },
  {
    id: 'WO-2025-006',
    number: 'WO-2025-006',
    name: 'Security Audit & Fixes',
    client: 'FinanceHub Corp',
    status: 'Pending',
    priority: 'Critical',
    type: 'direct',
    billable: true,
    rate: 1500,
    currency: '₹',
    startDate: '2025-11-17',
    dueDate: '2025-12-10',
    estimatedHours: 80,
    actualHours: 0,
    billingPolicy: 'Per hour worked',
    description: 'Comprehensive security audit and vulnerability fixes',
    lastActivity: 'Scheduled',
    owner: 'user-vijay', // Vijay owns this
    ownerName: 'Vijay Kumar',
    department: 'QA',
  },
  // Add Niranjan's specific design work orders
  {
    id: 'WO-2847',
    number: 'WO-2847',
    name: 'UI UX Design',
    client: 'The Process Internal',
    status: 'In Progress',
    priority: 'High',
    type: 'direct',
    billable: false,
    rate: 0,
    currency: '₹',
    startDate: '2025-11-15',
    dueDate: '2025-12-31',
    estimatedHours: 160,
    actualHours: 42,
    billingPolicy: 'Internal project',
    description: 'Complete UI/UX design for FLOWLOG time tracking application',
    lastActivity: '1 hour ago',
    owner: 'user-niranjan', // Niranjan owns this
    ownerName: 'Niranjan Raghavan',
    department: 'Design',
  },
  // Add Vijay's testing work order
  {
    id: 'WO-3921',
    number: 'WO-3921',
    name: 'Testing Suite',
    client: 'The Process Internal',
    status: 'In Progress',
    priority: 'High',
    type: 'direct',
    billable: false,
    rate: 0,
    currency: '₹',
    startDate: '2025-11-10',
    dueDate: '2026-01-15',
    estimatedHours: 200,
    actualHours: 38,
    billingPolicy: 'Internal project',
    description: 'Automated testing suite for all internal applications',
    lastActivity: '30 minutes ago',
    owner: 'user-vijay', // Vijay owns this
    ownerName: 'Vijay Kumar',
    department: 'QA',
  },
];

export const mockTimeEntries = [
  // Oct 17 (Friday)
  {
    id: '1',
    task: 'Component Development',
    workOrderId: 'WO-2025-001',
    workOrderType: 'direct',
    startTime: '09:00',
    endTime: '11:30',
    duration: 150,
    category: 'Work',
    billable: true,
    rate: 950,
    amount: 2375,
    date: '2025-10-17',
    approved: true,
  },
  {
    id: '2',
    task: 'Team Standup',
    workOrderId: 'WO-2025-001',
    workOrderType: 'direct',
    startTime: '11:30',
    endTime: '12:00',
    duration: 30,
    category: 'Meeting',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-17',
    approved: true,
    // Meeting metadata
    source: 'auto-logged',
    platform: 'google-meet',
    meetingLink: 'https://meet.google.com/team-standup',
    attendees: ['Arjun', 'Sarah Johnson', 'Michael Chen', 'Emily Rodriguez']
  },
  {
    id: '3',
    task: 'Lunch Break',
    workOrderId: null,
    startTime: '12:00',
    endTime: '13:00',
    duration: 60,
    category: 'Lunch',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-17',
    approved: true,
  },
  {
    id: '4',
    task: 'API Endpoint Testing',
    workOrderId: 'WO-2025-002',
    workOrderType: 'sequence',
    startTime: '13:00',
    endTime: '15:30',
    duration: 150,
    category: 'Work',
    billable: true,
    rate: 1150,
    amount: 2875,
    date: '2025-10-17',
    approved: false,
  },
  {
    id: '4a',
    task: 'Client Demo - Product Walkthrough',
    workOrderId: 'WO-2025-001',
    workOrderType: 'direct',
    startTime: '15:30',
    endTime: '16:30',
    duration: 60,
    category: 'Meeting',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-17',
    approved: false,
    // Meeting metadata
    source: 'auto-logged',
    platform: 'microsoft-teams',
    meetingLink: 'https://teams.microsoft.com/l/meetup/client-demo',
    attendees: ['Arjun', 'Client - TechCorp Inc.', 'Sarah Johnson']
  },
  {
    id: '5',
    task: 'Code Review',
    workOrderId: 'WO-2025-004',
    workOrderType: 'direct',
    startTime: '16:30',
    endTime: '17:30',
    duration: 60,
    category: 'Work',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-17',
    approved: false,
  },
  // Oct 16 (Thursday)
  {
    id: '6',
    task: 'Database Schema Design',
    workOrderId: 'WO-2025-003',
    workOrderType: 'sequence',
    startTime: '09:00',
    endTime: '12:00',
    duration: 180,
    category: 'Work',
    billable: true,
    rate: 1200,
    amount: 3600,
    date: '2025-10-16',
    approved: true,
  },
  {
    id: '6a',
    task: 'Architecture Discussion',
    workOrderId: 'WO-2025-003',
    workOrderType: 'sequence',
    startTime: '13:00',
    endTime: '14:00',
    duration: 60,
    category: 'Meeting',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-16',
    approved: true,
    // Meeting metadata
    source: 'auto-logged',
    platform: 'google-meet',
    meetingLink: 'https://meet.google.com/architecture-sync',
    attendees: ['Arjun', 'Sarah Johnson', 'Michael Chen', 'Tech Lead']
  },
  {
    id: '7',
    task: 'Client Meeting',
    workOrderId: 'WO-2025-001',
    workOrderType: 'direct',
    startTime: '14:00',
    endTime: '15:30',
    duration: 90,
    category: 'Meeting',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-16',
    approved: true,
    // Meeting metadata
    source: 'auto-logged',
    platform: 'microsoft-teams',
    meetingLink: 'https://teams.microsoft.com/l/meetup/client-sync',
    attendees: ['Arjun', 'Client - TechCorp Inc.', 'Project Manager']
  },
  // Oct 15 (Wednesday)
  {
    id: '7a',
    task: 'Daily Sync Meeting',
    workOrderId: null,
    startTime: '09:00',
    endTime: '09:30',
    duration: 30,
    category: 'Meeting',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-15',
    approved: true,
    // Meeting metadata
    source: 'auto-logged',
    platform: 'google-meet',
    meetingLink: 'https://meet.google.com/daily-sync',
    attendees: ['Arjun', 'Full Team - 12 participants']
  },
  {
    id: '8',
    task: 'Bug Fixes',
    workOrderId: 'WO-2025-002',
    workOrderType: 'sequence',
    startTime: '10:00',
    endTime: '13:00',
    duration: 180,
    category: 'Work',
    billable: true,
    rate: 1150,
    amount: 3450,
    date: '2025-10-15',
    approved: true,
  },
  {
    id: '9',
    task: 'Documentation',
    workOrderId: 'WO-2025-004',
    workOrderType: 'direct',
    startTime: '14:00',
    endTime: '16:00',
    duration: 120,
    category: 'Work',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-15',
    approved: true,
  },
  // Oct 14 (Tuesday)
  {
    id: '10',
    task: 'Sprint Planning',
    workOrderId: null,
    startTime: '09:30',
    endTime: '11:00',
    duration: 90,
    category: 'Meeting',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-14',
    approved: true,
    // Meeting metadata
    source: 'auto-logged',
    platform: 'microsoft-teams',
    meetingLink: 'https://teams.microsoft.com/l/meetup/sprint-planning',
    attendees: ['Arjun', 'Development Team', 'Product Owner', 'Scrum Master']
  },
  {
    id: '11',
    task: 'Feature Implementation',
    workOrderId: 'WO-2025-001',
    workOrderType: 'direct',
    startTime: '11:00',
    endTime: '16:00',
    duration: 300,
    category: 'Work',
    billable: true,
    rate: 950,
    amount: 4750,
    date: '2025-10-14',
    approved: true,
  },
  // Oct 13 (Monday)
  {
    id: '12',
    task: 'Weekly Sync',
    workOrderId: null,
    startTime: '09:00',
    endTime: '10:00',
    duration: 60,
    category: 'Meeting',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-13',
    approved: true,
    // Meeting metadata
    source: 'auto-logged',
    platform: 'google-meet',
    meetingLink: 'https://meet.google.com/weekly-sync',
    attendees: ['Arjun', 'All Hands - 25 participants']
  },
  {
    id: '13',
    task: 'UI Component Library',
    workOrderId: 'WO-2025-004',
    workOrderType: 'direct',
    startTime: '10:30',
    endTime: '15:00',
    duration: 270,
    category: 'Work',
    billable: false,
    rate: 0,
    amount: 0,
    date: '2025-10-13',
    approved: true,
  },
];

export const mockProcessHierarchy = [
  {
    id: 'mp-1',
    name: 'Software Development',
    type: 'main',
    children: [
      {
        id: 'kp-1',
        name: 'Frontend Development',
        type: 'key',
        children: [
          {
            id: 'p-1',
            name: 'Component Building',
            type: 'process',
            children: [
              { id: 's-1', name: 'Design Review', type: 'step' },
              { id: 's-2', name: 'Implementation', type: 'step' },
              { id: 's-3', name: 'Testing', type: 'step' },
            ],
          },
          {
            id: 'p-2',
            name: 'State Management',
            type: 'process',
            children: [
              { id: 's-4', name: 'Architecture Planning', type: 'step' },
              { id: 's-5', name: 'Implementation', type: 'step' },
            ],
          },
        ],
      },
      {
        id: 'kp-2',
        name: 'Backend Development',
        type: 'key',
        children: [
          {
            id: 'p-3',
            name: 'API Development',
            type: 'process',
            children: [
              { id: 's-6', name: 'Endpoint Design', type: 'step' },
              { id: 's-7', name: 'Implementation', type: 'step' },
              { id: 's-8', name: 'Documentation', type: 'step' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'mp-2',
    name: 'Project Management',
    type: 'main',
    children: [
      {
        id: 'kp-3',
        name: 'Planning',
        type: 'key',
        children: [
          {
            id: 'p-4',
            name: 'Sprint Planning',
            type: 'process',
            children: [
              { id: 's-9', name: 'Backlog Review', type: 'step' },
              { id: 's-10', name: 'Task Estimation', type: 'step' },
            ],
          },
        ],
      },
    ],
  },
];

export const mockWeeklyData = [
  { day: 'Mon', hours: 7.5, focus: 6.2 },
  { day: 'Tue', hours: 8.0, focus: 7.1 },
  { day: 'Wed', hours: 6.5, focus: 5.8 },
  { day: 'Thu', hours: 8.5, focus: 7.8 },
  { day: 'Fri', hours: 7.0, focus: 6.5 },
  { day: 'Sat', hours: 0, focus: 0 },
  { day: 'Sun', hours: 0, focus: 0 },
];

export const mockProjectBreakdown = [
  { name: 'Mobile App Redesign', hours: 18, color: '#4B5CFB' },
  { name: 'API Integration', hours: 12, color: '#00C7B7' },
  { name: 'UI Component Library', hours: 8, color: '#F0BB00' },
  { name: 'Database Migration', hours: 5, color: '#FF4D4D' },
];

export const mockBadges = [
  {
    id: 'streak-7',
    name: '7 Day Streak',
    icon: 'flame',
    earned: true,
    date: '2025-10-15',
  },
  {
    id: 'focus-master',
    name: 'Focus Master',
    description: '10 hours of deep work in one week',
    icon: 'target',
    earned: true,
    date: '2025-10-12',
  },
  {
    id: 'early-bird',
    name: 'Early Bird',
    description: 'Started work before 8 AM for 5 days',
    icon: 'sunrise',
    earned: false,
  },
  {
    id: 'century',
    name: 'Century Club',
    description: 'Logged 100 hours',
    icon: 'trophy',
    earned: true,
    date: '2025-10-01',
  },
];

export const mockTeamMembers = [
  {
    id: '1',
    name: 'Sarah Johnson',
    role: 'Frontend Developer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    hoursThisWeek: 38.5,
    status: 'approved',
  },
  {
    id: '2',
    name: 'Michael Chen',
    role: 'Backend Developer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    hoursThisWeek: 42.0,
    status: 'pending',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    role: 'UI/UX Designer',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    hoursThisWeek: 35.5,
    status: 'approved',
  },
];

export const categories = [
  { id: 'work', name: 'Work', color: '#4B5CFB' },
  { id: 'meeting', name: 'Meeting', color: '#00C7B7' },
  { id: 'lunch', name: 'Lunch', color: '#F0BB00' },
  { id: 'break', name: 'Break', color: '#FF4D4D' },
  { id: 'travel', name: 'Travel', color: '#00D68F' },
];

// Quick activity types (non-work-order activities)
export const quickActivities = [
  {
    id: 'lunch',
    name: 'Lunch Break',
    icon: 'utensils',
    color: '#F0BB00',
    description: 'Take a lunch break',
    billable: false,
  },
  {
    id: 'meeting',
    name: 'Meeting',
    icon: 'users',
    color: '#00C7B7',
    description: 'Team meeting or discussion',
    billable: false,
  },
  {
    id: 'discussion',
    name: 'Discussion',
    icon: 'message-circle',
    color: '#4B5CFB',
    description: 'Quick discussion or sync',
    billable: false,
  },
  {
    id: 'outpass',
    name: 'Outpass',
    icon: 'door-open',
    color: '#FF4D4D',
    description: 'Out of office',
    billable: false,
  },
  {
    id: 'other',
    name: 'Other',
    icon: 'edit',
    color: '#8B5CF6',
    description: 'Other activity (specify reason)',
    billable: false,
  },
];

// Other activities (Lunch, Meeting, etc.) - formatted for Work Order Selector
export const mockOtherActivities = [
  {
    id: 'OTHER-001',
    number: 'Lunch',
    name: 'Lunch Break',
    client: 'Personal',
    status: 'Available',
    priority: 'Normal',
    type: 'others',
    billable: false,
    rate: 0,
    currency: '₹',
    description: 'Take a lunch break',
    lastActivity: 'Always available',
  },
  {
    id: 'OTHER-002',
    number: 'Meetings',
    name: 'Team Meetings',
    client: 'Internal',
    status: 'Available',
    priority: 'Normal',
    type: 'others',
    billable: false,
    rate: 0,
    currency: '₹',
    description: 'Team meetings, standups, or sync calls',
    lastActivity: 'Always available',
  },
  {
    id: 'OTHER-003',
    number: 'Discussion',
    name: 'Discussion / Sync',
    client: 'Internal',
    status: 'Available',
    priority: 'Normal',
    type: 'others',
    billable: false,
    rate: 0,
    currency: '₹',
    description: 'Quick discussions or one-on-ones',
    lastActivity: 'Always available',
  },
  {
    id: 'OTHER-004',
    number: 'Outpass',
    name: 'Out of Office',
    client: 'Personal',
    status: 'Available',
    priority: 'Normal',
    type: 'others',
    billable: false,
    rate: 0,
    currency: '₹',
    description: 'Out of office or personal leave',
    lastActivity: 'Always available',
  },
  {
    id: 'OTHER-005',
    number: 'Others',
    name: 'Other Activities',
    client: 'General',
    status: 'Available',
    priority: 'Normal',
    type: 'others',
    billable: false,
    rate: 0,
    currency: '₹',
    description: 'Any other miscellaneous activity',
    lastActivity: 'Always available',
  },
];

// Calendar-specific data for Flow Calendar module
export const mockCalendarEntries = [
  // Oct 23 (Today - Thursday)
  {
    id: 'cal-1',
    task: 'Deep Work Session',
    workOrderId: 'WO-2025-001',
    startTime: '09:00',
    endTime: '11:30',
    duration: 150,
    category: 'work',
    billable: true,
    date: '2025-10-23',
    flowScore: 92,
    mood: '😃',
    planned: true,
    actual: true,
  },
  {
    id: 'cal-2',
    task: 'Team Standup',
    workOrderId: null,
    startTime: '11:30',
    endTime: '12:00',
    duration: 30,
    category: 'meeting',
    billable: false,
    date: '2025-10-23',
    flowScore: 65,
    mood: '😃',
    planned: true,
    actual: true,
  },
  {
    id: 'cal-3',
    task: 'Lunch Break',
    workOrderId: null,
    startTime: '12:00',
    endTime: '13:00',
    duration: 60,
    category: 'lunch',
    billable: false,
    date: '2025-10-23',
    flowScore: 0,
    mood: '😐',
    planned: true,
    actual: true,
  },
  {
    id: 'cal-4',
    task: 'Code Review & Debugging',
    workOrderId: 'WO-2025-002',
    startTime: '13:00',
    endTime: '15:30',
    duration: 150,
    category: 'work',
    billable: true,
    date: '2025-10-23',
    flowScore: 88,
    mood: '😃',
    planned: true,
    actual: true,
  },
  {
    id: 'cal-5',
    task: 'Client Presentation',
    workOrderId: 'WO-2025-001',
    startTime: '15:30',
    endTime: '16:30',
    duration: 60,
    category: 'meeting',
    billable: false,
    date: '2025-10-23',
    flowScore: 78,
    mood: '😐',
    planned: true,
    actual: false, // Planned but not logged yet
  },
  // Oct 22 (Yesterday - Wednesday)
  {
    id: 'cal-6',
    task: 'Feature Development',
    workOrderId: 'WO-2025-004',
    startTime: '09:30',
    endTime: '12:00',
    duration: 150,
    category: 'work',
    billable: true,
    date: '2025-10-22',
    flowScore: 95,
    mood: '😃',
    planned: true,
    actual: true,
  },
  {
    id: 'cal-7',
    task: 'Architecture Review',
    workOrderId: 'WO-2025-003',
    startTime: '14:00',
    endTime: '16:00',
    duration: 120,
    category: 'work',
    billable: true,
    date: '2025-10-22',
    flowScore: 85,
    mood: '😃',
    planned: true,
    actual: true,
  },
  // Oct 21 (Tuesday)
  {
    id: 'cal-8',
    task: 'Sprint Planning',
    workOrderId: null,
    startTime: '09:00',
    endTime: '11:00',
    duration: 120,
    category: 'meeting',
    billable: false,
    date: '2025-10-21',
    flowScore: 70,
    mood: '',
    planned: true,
    actual: true,
  },
  {
    id: 'cal-9',
    task: 'API Development',
    workOrderId: 'WO-2025-002',
    startTime: '11:00',
    endTime: '15:00',
    duration: 240,
    category: 'work',
    billable: true,
    date: '2025-10-21',
    flowScore: 90,
    mood: '😃',
    planned: true,
    actual: true,
  },
];

// Daily flow scores for heatmap (last 30 days)
export const mockDailyFlowScores = [
  { date: '2025-09-24', score: 78 },
  { date: '2025-09-25', score: 82 },
  { date: '2025-09-26', score: 75 },
  { date: '2025-09-27', score: 88 },
  { date: '2025-09-28', score: 0 }, // Weekend
  { date: '2025-09-29', score: 0 }, // Weekend
  { date: '2025-09-30', score: 85 },
  { date: '2025-10-01', score: 90 },
  { date: '2025-10-02', score: 87 },
  { date: '2025-10-03', score: 92 },
  { date: '2025-10-04', score: 84 },
  { date: '2025-10-05', score: 0 }, // Weekend
  { date: '2025-10-06', score: 0 }, // Weekend
  { date: '2025-10-07', score: 88 },
  { date: '2025-10-08', score: 91 },
  { date: '2025-10-09', score: 86 },
  { date: '2025-10-10', score: 89 },
  { date: '2025-10-11', score: 93 },
  { date: '2025-10-12', score: 0 }, // Weekend
  { date: '2025-10-13', score: 0 }, // Weekend
  { date: '2025-10-14', score: 87 },
  { date: '2025-10-15', score: 90 },
  { date: '2025-10-16', score: 85 },
  { date: '2025-10-17', score: 88 },
  { date: '2025-10-18', score: 92 },
  { date: '2025-10-19', score: 0 }, // Weekend
  { date: '2025-10-20', score: 0 }, // Weekend
  { date: '2025-10-21', score: 90 },
  { date: '2025-10-22', score: 95 },
  { date: '2025-10-23', score: 82 },
];

// AI insights and tips
export const mockAIInsights = [
  {
    id: 'insight-1',
    title: 'Peak Focus Window',
    description: 'Your best focus happens between 09:30–11:00. Schedule deep work here.',
    type: 'productivity',
    icon: 'zap',
  },
  {
    id: 'insight-2',
    title: 'Meeting Fatigue',
    description: 'You have 3+ meetings tomorrow. Consider blocking 2h for focused work.',
    type: 'warning',
    icon: 'alert-triangle',
  },
  {
    id: 'insight-3',
    title: 'Flow Streak',
    description: '5 days with Flow Score > 85. Keep the momentum going!',
    type: 'achievement',
    icon: 'trending-up',
  },
  {
    id: 'insight-4',
    title: 'Break Pattern',
    description: 'Taking breaks every 90 mins increases your Flow Score by 12%.',
    type: 'tip',
    icon: 'coffee',
  },
];

// Billing data for Cost Sheet
export const mockClientBilling = [
  {
    id: 'client-1',
    client: 'TechCorp Inc.',
    workOrderId: 'WO-2025-001',
    billableHours: 15.5,
    amount: 14725,
    status: 'Approved',
    lastUpdated: '2025-10-17',
  },
  {
    id: 'client-2',
    client: 'StartupXYZ',
    workOrderId: 'WO-2025-002',
    billableHours: 8.5,
    amount: 9775,
    status: 'Pending',
    lastUpdated: '2025-10-17',
  },
  {
    id: 'client-3',
    client: 'Enterprise Solutions Ltd.',
    workOrderId: 'WO-2025-003',
    billableHours: 3.0,
    amount: 3600,
    status: 'Approved',
    lastUpdated: '2025-10-16',
  },
];

// Billing trend data (last 7 days)
export const mockBillingTrend = [
  { day: 'Mon', amount: 4750 },
  { day: 'Tue', amount: 0 },
  { day: 'Wed', amount: 2550 },
  { day: 'Thu', amount: 3600 },
  { day: 'Fri', amount: 4500 },
  { day: 'Sat', amount: 0 },
  { day: 'Sun', amount: 0 },
];

// Recent "Others" activity entries (includes Work Orders and Others)
export const mockRecentOthersActivities = [
  // Today - Oct 25 - Show all 5 possible types
  // 1. Direct Work Order
  {
    id: 'recent-today-direct',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Mobile responsive fixes for dashboard',
    date: '2025-10-25',
    duration: 140,
    durationMinutes: 140,
    startTime: '09:00',
    endTime: '11:20',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 950,
    workOrderId: 'WO-2025-001',
    task: 'Mobile responsive fixes for dashboard',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    workOrderOwner: 'user-niranjan',
    workOrderOwnerName: 'Niranjan Raghavan',
    loggedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  // 2. Sequence Work Order
  {
    id: 'recent-today-sequence',
    activityId: 'WO-2025-003',
    activityName: 'WO-2025-003',
    description: 'Backend API integration - Phase 2',
    date: '2025-10-25',
    duration: 180,
    durationMinutes: 180,
    startTime: '12:00',
    endTime: '15:00',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1200,
    workOrderId: 'WO-2025-003',
    task: 'Backend API integration - Phase 2',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    workOrderOwner: 'user-niranjan',
    workOrderOwnerName: 'Niranjan Raghavan',
    loggedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  // 3. General (Other Activity)
  {
    id: 'recent-today-general',
    activityId: 'OTHER-001',
    activityName: 'Work',
    description: 'Code review and documentation',
    date: '2025-10-25',
    duration: 90,
    durationMinutes: 90,
    startTime: '15:30',
    endTime: '17:00',
    category: 'Work',
    task: 'Code review and documentation',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    loggedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  // 4. Sub Work Order (Collaborative)
  {
    id: 'recent-today-subwo',
    activityId: 'WO-2025-002',
    activityName: 'WO-2025-002',
    description: 'Payment gateway UI components',
    date: '2025-10-25',
    duration: 120,
    durationMinutes: 120,
    startTime: '10:00',
    endTime: '12:00',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1150,
    workOrderId: 'WO-2025-002',
    task: 'Payment gateway UI components',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: true,
    workOrderOwner: 'user-vijay',
    workOrderOwnerName: 'Vijay Kumar',
    subWorkOrderId: 'SWO-2025-002-001',
    deliverable: 'Complete responsive UI components with dark mode support',
    reasonForRequest: 'Need frontend expertise for payment module as per project timeline',
    loggedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  // 5. Meeting - Auto-logged from Calendar (VIOLET CARD)
  {
    id: 'recent-today-meeting',
    activityId: 'MEETING-001',
    activityName: 'Client Meeting',
    description: 'Q4 Planning Discussion with Client',
    date: '2025-10-25',
    duration: 60,
    durationMinutes: 60,
    startTime: '14:00',
    endTime: '15:00',
    category: 'Meeting',
    workOrderType: 'meeting', // Special type for calendar-integrated meetings
    task: 'Q4 Planning Discussion with Client',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    loggedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    // Integration metadata - auto-logged from Google Calendar
    source: 'auto-logged',
    platform: 'google-meet',
    meetingLink: 'https://meet.google.com/q4-plan-xyz',
    attendees: ['Niranjan Raghavan', 'John Smith', 'Sarah Johnson']
  },
  // Older entries below...
  // Today - Oct 17
  {
    id: 'recent-today-1',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Mobile responsive fixes',
    date: '2025-10-17',
    duration: 140,
    durationMinutes: 140,
    startTime: '09:00',
    endTime: '11:20',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 950,
    workOrderId: 'WO-2025-001',
    task: 'Mobile responsive fixes',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    workOrderOwner: 'user-niranjan',
    workOrderOwnerName: 'Niranjan Raghavan',
    loggedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'recent-today-2',
    activityId: 'OTHER-001',
    activityName: 'Work',
    description: 'Work',
    date: '2025-10-17',
    duration: 115,
    durationMinutes: 115,
    startTime: '10:00',
    endTime: '11:55',
    category: 'Work',
    task: 'Work',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    loggedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'recent-today-3',
    activityId: 'OTHER-002',
    activityName: 'Meetings',
    description: 'Daily standup with team',
    date: '2025-10-17',
    duration: 15,
    durationMinutes: 15,
    startTime: '11:30',
    endTime: '11:45',
    category: 'Meeting',
    task: 'Daily standup with team',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    loggedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    // Integration metadata - auto-logged from Google Calendar
    source: 'auto-logged',
    platform: 'google-meet',
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    attendees: ['Niranjan Raghavan', 'Vijay Kumar', 'Priya Sharma', 'Arjun Patel']
  },
  {
    id: 'recent-today-4',
    activityId: 'WO-2025-002',
    activityName: 'WO-2025-002',
    description: 'Design review for payment gateway UI',
    date: '2025-10-17',
    duration: 90,
    durationMinutes: 90,
    startTime: '14:00',
    endTime: '15:30',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1150,
    workOrderId: 'WO-2025-002',
    task: 'Design review for payment gateway UI',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    workOrderOwner: 'user-vijay',
    workOrderOwnerName: 'Vijay Kumar',
    loggedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  // Auto-logged Google Meet - Client Call (Oct 17)
  {
    id: 'recent-today-5',
    activityId: 'MEETING-001',
    activityName: 'Client Meeting',
    description: 'Q4 Planning with ABC Corp',
    date: '2025-10-17',
    duration: 60,
    durationMinutes: 60,
    startTime: '16:00',
    endTime: '17:00',
    category: 'Meeting',
    task: 'Q4 Planning with ABC Corp',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    loggedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    // Integration metadata - auto-logged from Google Calendar
    source: 'auto-logged',
    platform: 'google-meet',
    meetingLink: 'https://meet.google.com/q4-plan-abc',
    attendees: ['Niranjan Raghavan', 'John Smith (ABC Corp)', 'Sarah Johnson (ABC Corp)']
  },
  // Auto-logged Microsoft Teams - Product Demo (Oct 17)
  {
    id: 'recent-today-6',
    activityId: 'MEETING-004',
    activityName: 'Product Demo',
    description: 'Product Demo - New Features Walkthrough',
    date: '2025-10-17',
    duration: 45,
    durationMinutes: 45,
    startTime: '13:00',
    endTime: '13:45',
    category: 'Meeting',
    task: 'Product Demo - New Features Walkthrough',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    loggedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    // Integration metadata - auto-logged from Microsoft Teams
    source: 'auto-logged',
    platform: 'teams',
    meetingLink: 'https://teams.microsoft.com/l/meetup/product-demo',
    attendees: ['Niranjan Raghavan', 'Product Team', 'Stakeholders - 8 participants']
  },
  // Auto-logged Zoom - Design Review (Oct 17)
  {
    id: 'recent-today-7',
    activityId: 'MEETING-005',
    activityName: 'Design Review',
    description: 'UI/UX Design Review Session',
    date: '2025-10-17',
    duration: 90,
    durationMinutes: 90,
    startTime: '10:00',
    endTime: '11:30',
    category: 'Meeting',
    task: 'UI/UX Design Review Session',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    loggedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    // Integration metadata - auto-logged from Zoom
    source: 'auto-logged',
    platform: 'zoom',
    meetingLink: 'https://zoom.us/j/design-review',
    attendees: ['Niranjan Raghavan', 'Design Team', 'Priya Sharma', 'Arjun Patel']
  },
  // Oct 18 - Tomorrow
  {
    id: 'recent-oct18-1',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Mobile responsive fixes',
    date: '2025-10-18',
    duration: 140,
    durationMinutes: 140,
    startTime: '09:00',
    endTime: '11:20',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 950,
    workOrderId: 'WO-2025-001',
    task: 'Mobile responsive fixes',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    workOrderOwner: 'user-niranjan',
    workOrderOwnerName: 'Niranjan Raghavan',
    loggedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'recent-oct18-2',
    activityId: 'OTHER-001',
    activityName: 'Work',
    description: 'Work',
    date: '2025-10-18',
    duration: 15,
    durationMinutes: 15,
    startTime: '11:30',
    endTime: '11:45',
    category: 'Work',
    task: 'Work',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    loggedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'recent-oct18-3',
    activityId: 'OTHER-002',
    activityName: 'Meetings',
    description: 'Daily standup with team',
    date: '2025-10-18',
    duration: 30,
    durationMinutes: 30,
    startTime: '12:00',
    endTime: '12:30',
    category: 'Meeting',
    task: 'Daily standup with team',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    loggedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    // Integration metadata - auto-logged from Google Calendar
    source: 'auto-logged',
    platform: 'google-meet',
    meetingLink: 'https://meet.google.com/xyz-abcd-efg',
    attendees: ['Niranjan Raghavan', 'Vijay Kumar', 'Priya Sharma']
  },
  {
    id: 'recent-oct18-4',
    activityId: 'WO-2025-002',
    activityName: 'WO-2025-002',
    description: 'Design review for payment gateway UI',
    date: '2025-10-18',
    duration: 90,
    durationMinutes: 90,
    startTime: '14:00',
    endTime: '15:30',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1150,
    workOrderId: 'WO-2025-002',
    task: 'Design review for payment gateway UI',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    workOrderOwner: 'user-vijay',
    workOrderOwnerName: 'Vijay Kumar',
    loggedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  // Auto-logged Microsoft Teams - Sprint Retrospective (Oct 18)
  {
    id: 'recent-oct18-5',
    activityId: 'MEETING-002',
    activityName: 'Sprint Retrospective',
    description: 'Sprint 24 Retrospective',
    date: '2025-10-18',
    duration: 45,
    durationMinutes: 45,
    startTime: '16:00',
    endTime: '16:45',
    category: 'Meeting',
    task: 'Sprint 24 Retrospective',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    loggedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    // Integration metadata - auto-logged from Microsoft Teams
    source: 'auto-logged',
    platform: 'teams',
    meetingLink: 'https://teams.microsoft.com/l/meetup/sprint-retro',
    attendees: ['Niranjan Raghavan', 'Full Dev Team']
  },
  // Auto-logged Zoom - Design Critique (Oct 18)
  {
    id: 'recent-oct18-6',
    activityId: 'MEETING-003',
    activityName: 'Design Critique',
    description: 'Weekly Design Review Session',
    date: '2025-10-18',
    duration: 75,
    durationMinutes: 75,
    startTime: '17:00',
    endTime: '18:15',
    category: 'Meeting',
    task: 'Weekly Design Review Session',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    loggedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    // Integration metadata - auto-logged from Zoom
    source: 'auto-logged',
    platform: 'zoom',
    meetingLink: 'https://zoom.us/j/1234567890',
    attendees: ['Niranjan Raghavan', 'Design Team', '+ 6 others']
  },
  // Oct 16 - Yesterday
  {
    id: 'recent-yesterday-1',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Mobile responsive fixes',
    date: '2025-10-16',
    duration: 140,
    durationMinutes: 140,
    startTime: '09:00',
    endTime: '11:20',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 950,
    workOrderId: 'WO-2025-001',
    task: 'Mobile responsive fixes',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    workOrderOwner: 'user-niranjan',
    workOrderOwnerName: 'Niranjan Raghavan',
    loggedAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(), // 26 hours ago (LOCKED)
  },
  {
    id: 'recent-yesterday-2',
    activityId: 'OTHER-002',
    activityName: 'Meetings',
    description: 'Daily standup with team',
    date: '2025-10-16',
    duration: 15,
    durationMinutes: 15,
    startTime: '11:30',
    endTime: '11:45',
    category: 'Meeting',
    task: 'Daily standup with team',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    loggedAt: new Date(Date.now() - 27 * 60 * 60 * 1000).toISOString(), // 27 hours ago (LOCKED)
    // Integration metadata - auto-logged from Google Meet
    source: 'auto-logged',
    platform: 'google-meet',
    meetingLink: 'https://meet.google.com/daily-standup-oct16',
    attendees: ['Niranjan Raghavan', 'Vijay Kumar', 'Team Members']
  },
  // Auto-logged Teams - All Hands Meeting (Oct 16)
  {
    id: 'recent-yesterday-3',
    activityId: 'MEETING-006',
    activityName: 'All Hands Meeting',
    description: 'Monthly All Hands - Company Updates',
    date: '2025-10-16',
    duration: 60,
    durationMinutes: 60,
    startTime: '13:00',
    endTime: '14:00',
    category: 'Meeting',
    task: 'Monthly All Hands - Company Updates',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    loggedAt: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(), // 28 hours ago (LOCKED)
    // Integration metadata - auto-logged from Microsoft Teams
    source: 'auto-logged',
    platform: 'teams',
    meetingLink: 'https://teams.microsoft.com/l/meetup/all-hands',
    attendees: ['Niranjan Raghavan', 'Entire Company - 50+ participants']
  },
  // COLLABORATIVE ENTRY: Niranjan logging time on Vijay's work order (Yesterday)
  {
    id: 'recent-collab-yesterday-1',
    activityId: 'WO-2025-002',
    activityName: 'WO-2025-002',
    description: 'Design review for payment gateway UI',
    date: '2025-10-16',
    duration: 90,
    durationMinutes: 90,
    startTime: '14:00',
    endTime: '15:30',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1150,
    workOrderId: 'WO-2025-002',
    task: 'Design review for payment gateway UI',
    // Collaboration metadata - Niranjan logging on Vijay's WO
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: true,
    workOrderOwner: 'user-vijay',
    workOrderOwnerName: 'Vijay Kumar',
    loggedAt: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(), // 28 hours ago (LOCKED)
    // Approval workflow
    approvalStatus: 'partially-approved',
    approvedMinutes: 60,
    rejectedMinutes: 30,
    pendingMinutes: 0,
    approvedBy: 'user-vijay',
    approvedAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
  },
  // Oct 15
  {
    id: 'recent-15-1',
    activityId: 'WO-2025-003',
    activityName: 'WO-2025-003',
    description: 'Database schema migration',
    date: '2025-10-15',
    duration: 180,
    durationMinutes: 180,
    startTime: '09:00',
    endTime: '12:00',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1200,
    workOrderId: 'WO-2025-003',
    task: 'Database schema migration',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    workOrderOwner: 'user-vijay',
    workOrderOwnerName: 'Vijay Kumar',
  },
  {
    id: 'recent-15-2',
    activityId: 'OTHER-001',
    activityName: 'Lunch',
    description: 'Lunch break',
    date: '2025-10-15',
    duration: 60,
    durationMinutes: 60,
    startTime: '13:00',
    endTime: '14:00',
    category: 'Lunch',
    task: 'Lunch break',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
  },
  // Oct 14
  {
    id: 'recent-14-1',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Implementing new navigation flow',
    date: '2025-10-14',
    duration: 155,
    durationMinutes: 155,
    startTime: '09:00',
    endTime: '11:35',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 950,
    workOrderId: 'WO-2025-001',
    task: 'Implementing new navigation flow',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    workOrderOwner: 'user-niranjan',
    workOrderOwnerName: 'Niranjan Raghavan',
  },
  {
    id: 'recent-14-2',
    activityId: 'OTHER-002',
    activityName: 'Meetings',
    description: 'Sprint planning meeting',
    date: '2025-10-14',
    duration: 90,
    durationMinutes: 90,
    startTime: '14:00',
    endTime: '15:30',
    category: 'Meeting',
    task: 'Sprint planning meeting',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
  },
  // COLLABORATIVE ENTRY: Vijay logging on Niranjan's work order (Oct 14)
  {
    id: 'recent-collab-14-1',
    activityId: 'WO-2025-004',
    activityName: 'WO-2025-004',
    description: 'Testing component library updates',
    date: '2025-10-14',
    duration: 75,
    durationMinutes: 75,
    startTime: '12:00',
    endTime: '13:15',
    category: 'Work',
    workOrderType: 'direct',
    billable: false,
    rate: 0,
    workOrderId: 'WO-2025-004',
    task: 'Testing component library updates',
    loggedBy: 'user-vijay',
    loggedByName: 'Vijay Kumar',
    isCollaborative: true,
    workOrderOwner: 'user-niranjan',
    workOrderOwnerName: 'Niranjan Raghavan',
    approvalStatus: 'pending',
    approvedMinutes: 0,
    rejectedMinutes: 0,
    pendingMinutes: 75,
  },
  // Oct 13
  {
    id: 'recent-13-1',
    activityId: 'WO-2025-002',
    activityName: 'WO-2025-002',
    description: 'Payment gateway integration testing',
    date: '2025-10-13',
    duration: 95,
    durationMinutes: 95,
    startTime: '10:00',
    endTime: '11:35',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1150,
    workOrderId: 'WO-2025-002',
    task: 'Payment gateway integration testing',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    workOrderOwner: 'user-vijay',
    workOrderOwnerName: 'Vijay Kumar',
  },
  {
    id: 'recent-13-2',
    activityId: 'OTHER-003',
    activityName: 'Discussion',
    description: 'Code review discussion with team',
    date: '2025-10-13',
    duration: 30,
    durationMinutes: 30,
    startTime: '14:15',
    endTime: '14:45',
    category: 'Discussion',
    task: 'Code review discussion with team',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
  },
  // Oct 12
  {
    id: 'recent-12-1',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Component refactoring and optimization',
    date: '2025-10-12',
    duration: 105,
    durationMinutes: 105,
    startTime: '09:00',
    endTime: '10:45',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 950,
    workOrderId: 'WO-2025-001',
    task: 'Component refactoring and optimization',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    workOrderOwner: 'user-niranjan',
    workOrderOwnerName: 'Niranjan Raghavan',
  },
  {
    id: 'recent-12-2',
    activityId: 'OTHER-004',
    activityName: 'Outpass',
    description: 'Bank work',
    date: '2025-10-12',
    duration: 120,
    durationMinutes: 120,
    startTime: '14:00',
    endTime: '16:00',
    category: 'Outpass',
    task: 'Bank work',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
  },
  // Oct 25
  {
    id: 'recent-1',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'UI/UX improvements for dashboard',
    date: '2025-10-25',
    duration: 125,
    durationMinutes: 125,
    startTime: '09:15',
    endTime: '11:20',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1200,
    workOrderId: 'WO-2025-001',
    task: 'UI/UX improvements for dashboard',
    // Collaboration metadata
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    workOrderOwner: 'user-niranjan',
    workOrderOwnerName: 'Niranjan Raghavan',
    loggedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
  },
  {
    id: 'recent-2',
    activityId: 'OTHER-001',
    activityName: 'Lunch',
    description: 'Team lunch at cafeteria',
    date: '2025-10-25',
    duration: 45,
    durationMinutes: 45,
    startTime: '13:00',
    endTime: '13:45',
    category: 'Lunch',
    task: 'Team lunch at cafeteria',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    loggedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), // 1 hour ago
  },
  {
    id: 'recent-3',
    activityId: 'WO-2025-003',
    activityName: 'WO-2025-003',
    description: 'Payment gateway integration testing',
    date: '2025-10-25',
    duration: 95,
    durationMinutes: 95,
    startTime: '14:00',
    endTime: '15:35',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1200,
    workOrderId: 'WO-2025-003',
    task: 'Payment gateway integration testing',
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: false,
    workOrderOwner: 'user-niranjan',
    workOrderOwnerName: 'Niranjan Raghavan',
    loggedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(), // 30 minutes ago
  },
  // COLLABORATIVE ENTRY: Vijay logging time on Niranjan's work order
  {
    id: 'recent-collab-1',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'QA testing for mobile app redesign',
    date: '2025-11-12',
    duration: 120,
    durationMinutes: 120,
    startTime: '10:00',
    endTime: '12:00',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 950,
    workOrderId: 'WO-2025-001',
    task: 'QA testing for mobile app redesign',
    // Collaboration metadata - Vijay logging on Niranjan's WO via Sub Work Order
    subWorkOrderId: 'WO-2025-001-SUB-001', // Link to the sub work order
    loggedBy: 'user-vijay',
    loggedByName: 'Vijay Kumar',
    isCollaborative: true,
    workOrderOwner: 'user-niranjan',
    workOrderOwnerName: 'Niranjan Raghavan',
    loggedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(), // 3 hours ago
    // Approval workflow
    approvalStatus: 'partially-approved', // 'pending' | 'approved' | 'rejected' | 'partially-approved'
    approvedMinutes: 90, // Owner approved 90 minutes out of 120
    rejectedMinutes: 0,
    pendingMinutes: 30, // 30 minutes still pending
    approvedBy: 'user-niranjan',
    approvedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), // Approved 1 hour ago
  },
  // COLLABORATIVE ENTRY: Vijay working on Sub WO - Oct 18
  {
    id: 'recent-collab-1b',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Mobile responsive fixes',
    date: '2025-10-18',
    duration: 140,
    durationMinutes: 140,
    startTime: '09:00',
    endTime: '11:20',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 950,
    workOrderId: 'WO-2025-001',
    task: 'Mobile responsive fixes',
    // Collaboration metadata - Vijay working on Sub WO
    subWorkOrderId: 'WO-2025-001-SUB-001',
    loggedBy: 'user-vijay',
    loggedByName: 'Vijay Kumar',
    isCollaborative: true,
    workOrderOwner: 'user-niranjan',
    workOrderOwnerName: 'Niranjan Raghavan',
    loggedAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(), // 3 days ago
  },
  // COLLABORATIVE ENTRY: Vijay working on Sub WO - Oct 16
  {
    id: 'recent-collab-1c',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Mobile responsive fixes',
    date: '2025-10-16',
    duration: 140,
    durationMinutes: 140,
    startTime: '09:00',
    endTime: '11:20',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 950,
    workOrderId: 'WO-2025-001',
    task: 'Mobile responsive fixes',
    // Collaboration metadata - Vijay working on Sub WO
    subWorkOrderId: 'WO-2025-001-SUB-001',
    loggedBy: 'user-vijay',
    loggedByName: 'Vijay Kumar',
    isCollaborative: true,
    workOrderOwner: 'user-niranjan',
    workOrderOwnerName: 'Niranjan Raghavan',
    loggedAt: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(), // 5 days ago
  },
  // COLLABORATIVE ENTRY: Vijay working on Sub WO - Oct 14
  {
    id: 'recent-collab-1d',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Implementing new navigation flow',
    date: '2025-10-14',
    duration: 135,
    durationMinutes: 135,
    startTime: '09:00',
    endTime: '11:15',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 950,
    workOrderId: 'WO-2025-001',
    task: 'Implementing new navigation flow',
    // Collaboration metadata - Vijay working on Sub WO
    subWorkOrderId: 'WO-2025-001-SUB-001',
    loggedBy: 'user-vijay',
    loggedByName: 'Vijay Kumar',
    isCollaborative: true,
    workOrderOwner: 'user-niranjan',
    workOrderOwnerName: 'Niranjan Raghavan',
    loggedAt: new Date(Date.now() - 168 * 60 * 60 * 1000).toISOString(), // 7 days ago
  },
  // COLLABORATIVE ENTRY: Vijay working on Sub WO - Oct 12
  {
    id: 'recent-collab-1e',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Bug fixes and testing',
    date: '2025-10-12',
    duration: 90,
    durationMinutes: 90,
    startTime: '14:00',
    endTime: '15:30',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 950,
    workOrderId: 'WO-2025-001',
    task: 'Bug fixes and testing',
    // Collaboration metadata - Vijay working on Sub WO
    subWorkOrderId: 'WO-2025-001-SUB-001',
    loggedBy: 'user-vijay',
    loggedByName: 'Vijay Kumar',
    isCollaborative: true,
    workOrderOwner: 'user-niranjan',
    workOrderOwnerName: 'Niranjan Raghavan',
    loggedAt: new Date(Date.now() - 216 * 60 * 60 * 1000).toISOString(), // 9 days ago
  },
  // COLLABORATIVE ENTRY: Niranjan logging time on Vijay's work order  
  {
    id: 'recent-collab-2',
    activityId: 'WO-2025-002',
    activityName: 'WO-2025-002',
    description: 'Design review for payment gateway UI',
    date: '2025-11-12',
    duration: 90,
    durationMinutes: 90,
    startTime: '14:00',
    endTime: '15:30',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1150,
    workOrderId: 'WO-2025-002',
    task: 'Design review for payment gateway UI',
    // Collaboration metadata - Niranjan logging on Vijay's WO
    loggedBy: 'user-niranjan',
    loggedByName: 'Niranjan Raghavan',
    isCollaborative: true,
    workOrderOwner: 'user-vijay',
    workOrderOwnerName: 'Vijay Kumar',
    loggedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(), // 4 hours ago
    // Approval workflow
    approvalStatus: 'approved', // Fully approved by Vijay
    approvedMinutes: 90, // All 90 minutes approved
    rejectedMinutes: 0,
    pendingMinutes: 0,
    approvedBy: 'user-vijay',
    approvedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // Approved 2 hours ago
  },
  // Yesterday - Oct 24 (These should be locked - >24 hours)
  {
    id: 'recent-4',
    activityId: 'WO-2025-002',
    activityName: 'WO-2025-002',
    description: 'Inventory module enhancements',
    date: '2025-10-24',
    duration: 180,
    durationMinutes: 180,
    startTime: '09:00',
    endTime: '12:00',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1150,
    workOrderId: 'WO-2025-002',
    task: 'Inventory module enhancements',
    loggedAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(), // 26 hours ago (LOCKED)
  },
  {
    id: 'recent-5',
    activityId: 'OTHER-002',
    activityName: 'Meetings',
    description: 'Daily standup with team',
    date: '2025-10-24',
    duration: 15,
    durationMinutes: 15,
    startTime: '10:30',
    endTime: '10:45',
    category: 'Meeting',
    loggedAt: new Date(Date.now() - 27 * 60 * 60 * 1000).toISOString(), // 27 hours ago (LOCKED)
  },
  {
    id: 'recent-6',
    activityId: 'WO-2025-004',
    activityName: 'WO-2025-004',
    description: 'Documentation updates',
    date: '2025-10-24',
    duration: 60,
    durationMinutes: 60,
    startTime: '15:30',
    endTime: '16:30',
    category: 'Work',
    workOrderType: 'direct',
    billable: false,
    rate: 0,
    loggedAt: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(), // 25 hours ago (LOCKED)
  },
  // Oct 23
  {
    id: 'recent-7',
    activityId: 'OTHER-001',
    activityName: 'Lunch',
    description: 'Lunch break',
    date: '2025-10-23',
    duration: 60,
    durationMinutes: 60,
    startTime: '13:00',
    endTime: '14:00',
    category: 'Lunch',
  },
  {
    id: 'recent-8',
    activityId: 'OTHER-003',
    activityName: 'Discussion',
    description: 'Code review discussion with Sarah',
    date: '2025-10-23',
    duration: 30,
    durationMinutes: 30,
    startTime: '11:15',
    endTime: '11:45',
    category: 'Discussion',
  },
  {
    id: 'recent-9',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Mobile responsive fixes',
    date: '2025-10-23',
    duration: 140,
    durationMinutes: 140,
    startTime: '09:00',
    endTime: '11:20',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1200,
  },
  // Oct 22
  {
    id: 'recent-10',
    activityId: 'OTHER-002',
    activityName: 'Meetings',
    description: 'Sprint planning meeting',
    date: '2025-10-22',
    duration: 90,
    durationMinutes: 90,
    startTime: '10:00',
    endTime: '11:30',
    category: 'Meeting',
  },
  {
    id: 'recent-11',
    activityId: 'WO-2025-003',
    activityName: 'WO-2025-003',
    description: 'API integration for payment module',
    date: '2025-10-22',
    duration: 210,
    durationMinutes: 210,
    startTime: '09:00',
    endTime: '12:30',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1200,
  },
  {
    id: 'recent-12',
    activityId: 'OTHER-001',
    activityName: 'Lunch',
    description: 'Lunch break',
    date: '2025-10-22',
    duration: 60,
    durationMinutes: 60,
    startTime: '13:00',
    endTime: '14:00',
    category: 'Lunch',
  },
  // Oct 21
  {
    id: 'recent-13',
    activityId: 'OTHER-004',
    activityName: 'Outpass',
    description: 'Bank work',
    date: '2025-10-21',
    duration: 120,
    durationMinutes: 120,
    startTime: '14:00',
    endTime: '16:00',
    category: 'Outpass',
  },
  {
    id: 'recent-14',
    activityId: 'WO-2025-002',
    activityName: 'WO-2025-002',
    description: 'Bug fixes in inventory system',
    date: '2025-10-21',
    duration: 165,
    durationMinutes: 165,
    startTime: '09:30',
    endTime: '12:15',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1150,
  },
  {
    id: 'recent-15',
    activityId: 'OTHER-003',
    activityName: 'Discussion',
    description: 'Quick sync with manager',
    date: '2025-10-21',
    duration: 20,
    durationMinutes: 20,
    startTime: '16:30',
    endTime: '16:50',
    category: 'Discussion',
  },
  // Oct 20 - Adding more entries for better activity history
  {
    id: 'recent-16',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Implementing new navigation flow',
    date: '2025-10-20',
    duration: 155,
    durationMinutes: 155,
    startTime: '09:00',
    endTime: '11:35',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1200,
  },
  {
    id: 'recent-17',
    activityId: 'WO-2025-003',
    activityName: 'WO-2025-003',
    description: 'Database schema updates for payment module',
    date: '2025-10-20',
    duration: 180,
    durationMinutes: 180,
    startTime: '13:00',
    endTime: '16:00',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1200,
  },
  // Oct 19
  {
    id: 'recent-18',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Component refactoring and optimization',
    date: '2025-10-19',
    duration: 105,
    durationMinutes: 105,
    startTime: '14:00',
    endTime: '15:45',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1200,
  },
  {
    id: 'recent-19',
    activityId: 'WO-2025-002',
    activityName: 'WO-2025-002',
    description: 'Code review and testing',
    date: '2025-10-19',
    duration: 120,
    durationMinutes: 120,
    startTime: '10:00',
    endTime: '12:00',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1150,
  },
  // Oct 18
  {
    id: 'recent-20',
    activityId: 'WO-2025-003',
    activityName: 'WO-2025-003',
    description: 'Payment API integration',
    date: '2025-10-18',
    duration: 195,
    durationMinutes: 195,
    startTime: '09:15',
    endTime: '12:30',
    category: 'Work',
    workOrderType: 'sequence',
    billable: true,
    rate: 1200,
  },
  {
    id: 'recent-21',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'Design implementation for mobile screens',
    date: '2025-10-18',
    duration: 165,
    durationMinutes: 165,
    startTime: '13:30',
    endTime: '16:15',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1200,
  },
  // Oct 16
  {
    id: 'recent-24',
    activityId: 'WO-2025-001',
    activityName: 'WO-2025-001',
    description: 'User feedback implementation',
    date: '2025-10-16',
    duration: 115,
    durationMinutes: 115,
    startTime: '10:00',
    endTime: '11:55',
    category: 'Work',
    workOrderType: 'direct',
    billable: true,
    rate: 1200,
  },
];

// === SUB WORK ORDERS ===
// Tracks Sub Work Orders assigned from main work orders
// Owner can assign Sub WO to team members, reducing their TAT
// Users can also request Sub WOs with estimated hours for owner approval
export const mockSubWorkOrders = [
  // Active: Niranjan assigned Sub WO to Vijay (Owner-initiated)
  {
    id: 'subwo-001',
    parentWorkOrderId: 'WO-2847',
    parentWorkOrderName: 'UI UX Design',
    parentWorkOrderTAT: 160,
    subWorkOrderNumber: 'WO-2847-SUB-001',
    subWorkOrderName: 'UI Testing & QA Review',
    assignedToId: 'user-vijay',
    assignedToName: 'Vijay Kumar',
    assignedToRole: 'QA Engineer',
    assignedById: 'user-niranjan',
    assignedByName: 'Niranjan Raghavan',
    allocatedHours: 6,
    allocatedMinutes: 360,
    usedMinutes: 180,
    remainingMinutes: 180,
    status: 'active' as const,
    deliverables: 'Complete UI testing, document bugs, provide QA report',
    startDate: '2025-11-10',
    dueDate: '2025-11-15',
    createdAt: '2025-11-10T09:00:00',
    approvedAt: '2025-11-10T09:00:00',
    completedAt: null,
    type: 'owner-initiated' as const,
  },
  
  // Pending Approval: Vijay submitted deliverables for Niranjan
  {
    id: 'subwo-002',
    parentWorkOrderId: 'WO-2025-001',
    parentWorkOrderName: 'Mobile App Redesign',
    parentWorkOrderTAT: 120,
    subWorkOrderNumber: 'WO-2025-001-SUB-001',
    subWorkOrderName: 'Mobile UI Bug Fixes Validation',
    assignedToId: 'user-vijay',
    assignedToName: 'Vijay Kumar',
    assignedToRole: 'QA Engineer',
    assignedById: 'user-niranjan',
    assignedByName: 'Niranjan Raghavan',
    allocatedHours: 3,
    allocatedMinutes: 180,
    usedMinutes: 165,
    remainingMinutes: 15,
    status: 'pending-approval' as const,
    deliverables: 'Validate all bug fixes, regression testing, sign-off report',
    deliverableNotes: 'Completed validation of 15 bug fixes. All tests passed. Ready for production deployment.',
    deliverableAttachments: [
      { name: 'validation-report.pdf', size: '1.8 MB', type: 'application/pdf' },
      { name: 'test-results.xlsx', size: '245 KB', type: 'application/xlsx' },
    ],
    startDate: '2025-11-11',
    dueDate: '2025-11-13',
    createdAt: '2025-11-10T11:00:00',
    approvedAt: '2025-11-10T11:30:00',
    completedAt: null,
    deliverableSubmittedAt: '2025-11-13T15:00:00',
    type: 'owner-initiated' as const,
  },
  
  // Pending Request: Vijay requesting Sub WO (needs approval)
  {
    id: 'subwo-003',
    parentWorkOrderId: 'WO-2847',
    parentWorkOrderName: 'UI UX Design',
    parentWorkOrderTAT: 160,
    subWorkOrderNumber: null,
    subWorkOrderName: 'Accessibility Testing & WCAG Compliance',
    assignedToId: 'user-vijay',
    assignedToName: 'Vijay Kumar',
    assignedToRole: 'QA Engineer',
    assignedById: 'user-niranjan',
    assignedByName: 'Niranjan Raghavan',
    ownerName: 'Niranjan Raghavan',
    workOrderName: 'UI UX Design',
    workOrderId: 'WO-2847',
    requestedHours: 8,
    allocatedHours: null,
    allocatedMinutes: null,
    usedMinutes: 0,
    remainingMinutes: null,
    status: 'pending' as const,
    deliverables: 'Complete WCAG 2.1 compliance testing, accessibility audit report, screen reader testing',
    requestReason: 'Accessibility testing is critical before production release. Need dedicated time for comprehensive WCAG audit.',
    startDate: '2025-11-14',
    dueDate: '2025-11-18',
    createdAt: '2025-11-12T10:00:00',
    approvedAt: null,
    completedAt: null,
    type: 'user-requested' as const,
  },
  
  // Pending Request: Vijay requesting another Sub WO for performance testing
  {
    id: 'subwo-003b',
    parentWorkOrderId: 'WO-2025-001',
    parentWorkOrderName: 'Mobile App Redesign',
    parentWorkOrderTAT: 120,
    subWorkOrderNumber: null,
    subWorkOrderName: 'Performance Testing & Load Analysis',
    assignedToId: 'user-vijay',
    assignedToName: 'Vijay Kumar',
    assignedToRole: 'QA Engineer',
    assignedById: 'user-niranjan',
    assignedByName: 'Niranjan Raghavan',
    ownerName: 'Niranjan Raghavan',
    workOrderName: 'Mobile App Redesign',
    workOrderId: 'WO-2025-001',
    requestedHours: 12,
    allocatedHours: null,
    allocatedMinutes: null,
    usedMinutes: 0,
    remainingMinutes: null,
    status: 'pending' as const,
    deliverables: 'Load testing with 1000+ concurrent users, performance benchmarking, optimization recommendations report with detailed metrics and analysis',
    requestReason: 'App is experiencing slowdowns during peak hours. Need dedicated time for comprehensive performance testing and analysis to identify bottlenecks before launch.',
    startDate: '2025-11-16',
    dueDate: '2025-11-22',
    createdAt: '2025-11-13T14:30:00',
    approvedAt: null,
    completedAt: null,
    type: 'user-requested' as const,
  },
  
  // Pending Request: Vijay requesting Sub WO for automation
  {
    id: 'subwo-003c',
    parentWorkOrderId: 'WO-2847',
    parentWorkOrderName: 'UI UX Design',
    parentWorkOrderTAT: 160,
    subWorkOrderNumber: null,
    subWorkOrderName: 'Test Automation Framework Setup',
    assignedToId: 'user-vijay',
    assignedToName: 'Vijay Kumar',
    assignedToRole: 'QA Engineer',
    assignedById: 'user-niranjan',
    assignedByName: 'Niranjan Raghavan',
    ownerName: 'Niranjan Raghavan',
    workOrderName: 'UI UX Design',
    workOrderId: 'WO-2847',
    requestedHours: 16,
    allocatedHours: null,
    allocatedMinutes: null,
    usedMinutes: 0,
    remainingMinutes: null,
    status: 'pending' as const,
    deliverables: 'Setup Cypress automation framework, create reusable test components, implement CI/CD integration, document automation best practices and guidelines',
    requestReason: 'Manual regression testing is taking too long. Setting up automation framework will save significant time in future sprints and improve test coverage quality.',
    startDate: '2025-11-20',
    dueDate: '2025-11-28',
    createdAt: '2025-11-14T09:15:00',
    approvedAt: null,
    completedAt: null,
    type: 'user-requested' as const,
  },
  
  // Completed: Niranjan worked on Vijay's WO
  {
    id: 'subwo-004',
    parentWorkOrderId: 'WO-3921',
    parentWorkOrderName: 'Testing Suite',
    parentWorkOrderTAT: 200,
    subWorkOrderNumber: 'WO-3921-SUB-001',
    subWorkOrderName: 'Test Dashboard UI Design',
    assignedToId: 'user-niranjan',
    assignedToName: 'Niranjan Raghavan',
    assignedToRole: 'UI/UX Designer',
    assignedById: 'user-vijay',
    assignedByName: 'Vijay Kumar',
    allocatedHours: 4,
    allocatedMinutes: 240,
    usedMinutes: 210,
    approvedMinutes: 210,
    remainingMinutes: 30,
    status: 'completed' as const,
    deliverables: 'Design test dashboard UI, create component mockups, design test report views',
    deliverableNotes: 'Completed all UI designs for test dashboard. Delivered 12 screens with interactive prototypes.',
    startDate: '2025-11-08',
    dueDate: '2025-11-10',
    createdAt: '2025-11-08T09:00:00',
    approvedAt: '2025-11-08T09:30:00',
    completedAt: '2025-11-10T16:00:00',
    deliverableApprovedAt: '2025-11-10T17:00:00',
    type: 'owner-initiated' as const,
  },
  
  // Pending Request: Niranjan requesting Sub WO for design system work
  {
    id: 'subwo-005',
    parentWorkOrderId: 'WO-3921',
    parentWorkOrderName: 'Testing Suite',
    parentWorkOrderTAT: 200,
    subWorkOrderNumber: null,
    subWorkOrderName: 'Design System Component Library',
    assignedToId: 'user-niranjan',
    assignedToName: 'Niranjan Raghavan',
    assignedToRole: 'UI/UX Designer',
    assignedById: 'user-vijay',
    assignedByName: 'Vijay Kumar',
    ownerName: 'Vijay Kumar',
    workOrderName: 'Testing Suite',
    workOrderId: 'WO-3921',
    requestedHours: 20,
    allocatedHours: null,
    allocatedMinutes: null,
    usedMinutes: 0,
    remainingMinutes: null,
    status: 'pending' as const,
    deliverables: 'Create comprehensive design system with reusable components, design tokens, color palette documentation, typography scale, spacing system, and component usage guidelines with interactive examples',
    requestReason: 'The testing suite needs consistent UI components across all test modules. Building a design system will ensure visual consistency and speed up future development with reusable components.',
    startDate: '2025-11-20',
    dueDate: '2025-12-02',
    createdAt: '2025-11-15T11:20:00',
    approvedAt: null,
    completedAt: null,
    type: 'user-requested' as const,
  },
  
  // Active: Vijay approved Niranjan's request - now active
  {
    id: 'subwo-006b',
    parentWorkOrderId: 'WO-2025-003',
    parentWorkOrderName: 'Database Migration Project',
    parentWorkOrderTAT: 90,
    subWorkOrderNumber: 'WO-2025-003-SUB-001',
    subWorkOrderName: 'Database Schema UI Design & Documentation',
    assignedToId: 'user-niranjan',
    assignedToName: 'Niranjan Raghavan',
    assignedToRole: 'UI/UX Designer',
    assignedById: 'user-vijay',
    assignedByName: 'Vijay Kumar',
    allocatedHours: 10,
    allocatedMinutes: 600,
    usedMinutes: 240,
    remainingMinutes: 360,
    status: 'active' as const,
    deliverables: 'Design database schema visualization UI, create documentation template designs, design admin panel mockups for database management',
    startDate: '2025-11-12',
    dueDate: '2025-11-20',
    createdAt: '2025-11-11T10:30:00',
    approvedAt: '2025-11-11T14:00:00',
    completedAt: null,
    type: 'user-requested' as const,
  },
  
  // Pending Request: Niranjan requesting Sub WO for user research
  {
    id: 'subwo-006',
    parentWorkOrderId: 'WO-2025-002',
    parentWorkOrderName: 'API Integration - Payment Gateway',
    parentWorkOrderTAT: 80,
    subWorkOrderNumber: null,
    subWorkOrderName: 'Payment Flow UX Research & Optimization',
    assignedToId: 'user-niranjan',
    assignedToName: 'Niranjan Raghavan',
    assignedToRole: 'UI/UX Designer',
    assignedById: 'user-vijay',
    assignedByName: 'Vijay Kumar',
    ownerName: 'Vijay Kumar',
    workOrderName: 'API Integration - Payment Gateway',
    workOrderId: 'WO-2025-002',
    requestedHours: 14,
    allocatedHours: null,
    allocatedMinutes: null,
    usedMinutes: 0,
    remainingMinutes: null,
    status: 'pending' as const,
    deliverables: 'Conduct user interviews with 10+ users, analyze payment flow friction points, create detailed user journey maps, design improved checkout experience with reduced steps, provide A/B testing recommendations',
    requestReason: 'Current payment flow has 40% drop-off rate. Need dedicated time for comprehensive UX research to identify pain points and redesign the checkout experience to improve conversion rates significantly.',
    startDate: '2025-11-22',
    dueDate: '2025-12-01',
    createdAt: '2025-11-16T09:45:00',
    approvedAt: null,
    completedAt: null,
    type: 'user-requested' as const,
  },
  
  // Pending Request: Niranjan requesting Sub WO for mobile wireframes
  {
    id: 'subwo-007',
    parentWorkOrderId: 'WO-3921',
    parentWorkOrderName: 'Testing Suite',
    parentWorkOrderTAT: 200,
    subWorkOrderNumber: null,
    subWorkOrderName: 'Mobile App Wireframes & Prototypes',
    assignedToId: 'user-niranjan',
    assignedToName: 'Niranjan Raghavan',
    assignedToRole: 'UI/UX Designer',
    assignedById: 'user-vijay',
    assignedByName: 'Vijay Kumar',
    ownerName: 'Vijay Kumar',
    workOrderName: 'Testing Suite',
    workOrderId: 'WO-3921',
    requestedHours: 18,
    allocatedHours: null,
    allocatedMinutes: null,
    usedMinutes: 0,
    remainingMinutes: null,
    status: 'pending' as const,
    deliverables: 'Design complete mobile app wireframes for iOS and Android, create high-fidelity interactive prototypes, design responsive layouts for all screen sizes, document gesture interactions and transitions, include accessibility considerations',
    requestReason: 'Testing suite needs mobile support urgently. Creating detailed wireframes and prototypes upfront will prevent costly redesigns later and ensure proper mobile-first approach with native platform patterns.',
    startDate: '2025-11-25',
    dueDate: '2025-12-08',
    createdAt: '2025-11-17T14:10:00',
    approvedAt: null,
    completedAt: null,
    type: 'user-requested' as const,
  },
];

// Sub Work Orders are now the single source of truth for collaboration
// No separate deliverable submissions - they're part of the Sub WO workflow

// Reports Module Mock Data
export const mockReportsData = {
  // Last ERP sync time
  lastSync: '12:42',
  
  // Work Orders (Direct) Summary
  workOrdersDirect: {
    totalHours: 45.5,
    billableHours: 38.5,
    avgRate: 1033,
    totalAmount: 39770.5,
    entries: [
      {
        id: 'WO-2025-001',
        name: 'Mobile App Redesign',
        client: 'TechCorp Inc.',
        hours: 24.5,
        billableHours: 24.5,
        rate: 950,
        amount: 23275,
        approved: true,
      },
      {
        id: 'WO-2025-002',
        name: 'API Integration',
        client: 'StartupXYZ',
        hours: 14.0,
        billableHours: 14.0,
        rate: 1150,
        amount: 16100,
        approved: true,
      },
      {
        id: 'WO-2025-004',
        name: 'UI Component Library',
        client: 'Internal',
        hours: 7.0,
        billableHours: 0,
        rate: 0,
        amount: 0,
        approved: true,
      },
    ],
    missingRateCount: 0,
  },
  
  // Process-Sequence Work Orders Summary
  workOrdersSequence: {
    totalHours: 32.0,
    billableHours: 32.0,
    avgRate: 1200,
    totalAmount: 38400,
    entries: [
      {
        id: 'WO-2025-003',
        name: 'Database Migration',
        client: 'Enterprise Solutions Ltd.',
        hours: 32.0,
        billableHours: 32.0,
        rate: 1200,
        amount: 38400,
        approved: true,
        hierarchy: {
          main: 'Infrastructure',
          key: 'Database Services',
          process: 'Migration',
          steps: [
            { name: 'Assessment & Planning', hours: 12.0, rate: 1200, amount: 14400, approved: true },
            { name: 'Data Backup', hours: 8.0, rate: 1200, amount: 9600, approved: true },
            { name: 'Schema Migration', hours: 12.0, rate: 1200, amount: 14400, approved: true },
          ],
        },
      },
    ],
    missingRateCount: 0,
  },
  
  // General Activities Summary
  generalActivities: {
    totalHours: 12.5,
    billableHours: 0,
    entries: [
      { category: 'Meeting', hours: 4.5, color: '#00C7B7' },
      { category: 'Lunch', hours: 5.0, color: '#F0BB00' },
      { category: 'Break', hours: 2.0, color: '#FF8A00' },
      { category: 'Discussion', hours: 1.0, color: '#8B5CF6' },
    ],
  },
  
  // Sub Work Orders Summary (Collaborative Work)
  subWorkOrders: {
    totalHours: 12.0,
    billableHours: 12.0,
    avgRate: 1150,
    totalAmount: 13800,
    entries: [
      {
        id: 'SWO-2025-002-001',
        parentWorkOrderId: 'WO-2025-002',
        parentWorkOrderName: 'API Integration - Payment Gateway',
        name: 'Payment gateway UI components',
        workOrderOwner: 'Vijay Kumar',
        hours: 12.0,
        billableHours: 12.0,
        rate: 1150,
        amount: 13800,
        status: 'completed',
        deliverable: 'Complete responsive UI components with dark mode support',
      },
    ],
  },
  
  // Meetings Summary (Calendar-integrated)
  meetings: {
    totalHours: 8.5,
    billableHours: 0,
    entries: [
      {
        id: 'MEETING-001',
        name: 'Q4 Planning Discussion with Client',
        platform: 'google-meet',
        hours: 1.0,
        attendees: 3,
        source: 'auto-logged',
      },
      {
        id: 'MEETING-002',
        name: 'Team Stand-up',
        platform: 'google-meet',
        hours: 0.5,
        attendees: 5,
        source: 'auto-logged',
      },
      {
        id: 'MEETING-003',
        name: 'Sprint Planning',
        platform: 'zoom',
        hours: 2.0,
        attendees: 8,
        source: 'auto-logged',
      },
      {
        id: 'MEETING-004',
        name: 'Design Review',
        platform: 'google-meet',
        hours: 1.5,
        attendees: 4,
        source: 'auto-logged',
      },
      {
        id: 'MEETING-005',
        name: 'Client Presentation',
        platform: 'zoom',
        hours: 1.5,
        attendees: 6,
        source: 'auto-logged',
      },
      {
        id: 'MEETING-006',
        name: 'Weekly Sync',
        platform: 'google-meet',
        hours: 1.0,
        attendees: 7,
        source: 'auto-logged',
      },
      {
        id: 'MEETING-007',
        name: '1-on-1 with Manager',
        platform: 'google-meet',
        hours: 1.0,
        attendees: 2,
        source: 'auto-logged',
      },
    ],
  },
  
  // Totals
  totals: {
    totalLoggedHours: 110.5,
    totalBillableHours: 82.5,
    totalNonBillableHours: 28.0,
    totalBillableAmount: 91970.5,
  },
  
  // Integrity flags
  hasMultiCurrency: false,
  missingRateEntries: [],
  pendingApprovalHours: 2.5,
};